export const TODOS_LOADED = "TODOS_LOADED";
export const TODOS_CREATED = "TODOS_CREATED";
export const TODOS_UPDATED = "TODOS_UPDATED";
export const TODOS_DELETED = "TODOS_DELETED";
export const TODOS_LIMIT_UPDATED = "TODOS_LIMIT_UPDATED";
export const TODOS_STATUS_UPDATED = "TODOS_STATUS_UPDATED";

